# syntax=docker/dockerfile:1

FROM python:3.8-slim-buster

WORKDIR /python-app

COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

ENV PORT=5001

EXPOSE ${PORT}

ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=0.0.0.0

CMD ["sh", "-c", "flask run --host=0.0.0.0 --port=$PORT"]