apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: dev
    server: "https://argocd.local"
  project: default
  source:
    path: manifests
    repoURL: "https://github.com/rafaelhueb92/ingress-service-flask-k8s"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true